scipy matrix

In [1]:
import scipy

In [2]:
import numpy as np
import scipy
from scipy import linalg

A = np.array([[1,3,5],[2,5,1],[2,3,8]])

print(A)

print(linalg.inv(A))

print(A.dot(linalg.inv(A)) )


[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
[[ 1.00000000e+00 -1.11022302e-16  4.85722573e-17]
 [ 3.05311332e-16  1.00000000e+00  7.63278329e-17]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]
